#!/usr/bin/env bash
# Shared bootstrap logic, sourced by both images/harness/entrypoint.sh and
# images/paperclip/entrypoint.sh. Not meant to be run directly.
#
# See specs/archive/260927-agentic-team-w-paperclip/architecture.md for the instance.yaml schema and
# configuration-docs/credentials-and-secrets.md for how *_ref fields resolve to real values.
set -euo pipefail

INSTANCE_CONFIG="/data/instance.yaml"
DEFAULT_INSTANCE_CONFIG="/opt/agentic-team/instance.default.yaml"
HERMES_HOME="${HOME}/.hermes"
# TODO(verify): this default poll interval is our own choice for FR-021's "sensible default", not
# sourced from Hermes/Paperclip docs. Every 5 minutes.
DEFAULT_POLL_CRON="*/5 * * * *"

if [ ! -f "${INSTANCE_CONFIG}" ]; then
  echo "[entrypoint] no ${INSTANCE_CONFIG} found — bootstrapping default configuration (FR-025)"
  mkdir -p "$(dirname "${INSTANCE_CONFIG}")"
  cp "${DEFAULT_INSTANCE_CONFIG}" "${INSTANCE_CONFIG}"
else
  echo "[entrypoint] found existing ${INSTANCE_CONFIG} — reusing it (FR-026)"
fi

# Resolve *_ref fields against this container's own environment and apply them into Hermes's
# config. yq (mikefarah/yq) is used for YAML reads/writes — installed in the Dockerfile.
PAPERCLIP_AGENT_ID="$(yq '.paperclip.agent_id' "${INSTANCE_CONFIG}")"
PAPERCLIP_API_KEY_REF="$(yq '.paperclip.api_key_ref' "${INSTANCE_CONFIG}")"
GITHUB_BOT_REF="$(yq '.identity.github_bot_account_ref' "${INSTANCE_CONFIG}")"

mkdir -p "${HERMES_HOME}"
{
  echo "# Generated by entrypoint.sh from ${INSTANCE_CONFIG} — do not edit by hand."
  [ -n "${PAPERCLIP_API_KEY_REF}" ] && [ "${PAPERCLIP_API_KEY_REF}" != "null" ] && \
    echo "PAPERCLIP_AGENT_API_KEY=${!PAPERCLIP_API_KEY_REF:-}"
  [ -n "${GITHUB_BOT_REF}" ] && [ "${GITHUB_BOT_REF}" != "null" ] && \
    echo "GITHUB_TOKEN=${!GITHUB_BOT_REF:-}"
} > "${HERMES_HOME}/.env"

POLL_COMMAND="paperclipai agent inbox-mine --user-id ${PAPERCLIP_AGENT_ID:-} --status todo,in_progress"
CRON_JOBS_FILE="${HERMES_HOME}/cron/jobs.json"

# Fix for review finding FR-007: this runs on every container start, not just the first. Whether
# `hermes cron create` itself dedupes an identical schedule+command is unconfirmed (see
# research.md), so guard explicitly by checking the jobs file for the exact command first —
# avoids accumulating duplicate poll jobs across restarts regardless of Hermes's own behavior.
if [ "${PAPERCLIP_AGENT_ID}" != "null" ] && [ -n "${PAPERCLIP_AGENT_ID}" ]; then
  if [ -f "${CRON_JOBS_FILE}" ] && grep -qF "${POLL_COMMAND}" "${CRON_JOBS_FILE}"; then
    echo "[entrypoint] a cron job for '${POLL_COMMAND}' already exists — not creating a duplicate"
  else
    hermes cron create "${DEFAULT_POLL_CRON}" "${POLL_COMMAND}" \
      || echo "[entrypoint] hermes cron create failed — continuing"
  fi
fi
