#!/usr/bin/env bash
# Shared bootstrap logic, sourced by both images/harness/entrypoint.sh and
# images/paperclip/entrypoint.sh. Not meant to be run directly.
#
# Responsibilities:
#   1. Bootstrap /data/instance.yaml from the image's default template on first start, or reuse an
#      existing one (this is why /data must be a persistent volume).
#   2. Resolve every instance.yaml field into a single generated env file (~/.hermes/.env) —
#      `*_ref` fields dereferenced against this container's own environment, scalars exported
#      directly. See documentation/architectual-decisions-record.md ADR-0011 for why this project
#      does not write into Hermes's/OMP's/OpenCode's native config schemas.
#   3. Register the Paperclip work-poll cron job with Hermes, idempotently.
#
# Field reference: user-docs/configuration-reference.md
# Credential resolution: configuration-docs/credentials-and-secrets.md
set -euo pipefail

INSTANCE_CONFIG="/data/instance.yaml"
DEFAULT_INSTANCE_CONFIG="/opt/agentic-team/instance.default.yaml"
HERMES_HOME="${HOME}/.hermes"
HERMES_ENV_FILE="${HERMES_HOME}/.env"
# Our own choice for a sensible default, not sourced from Hermes/Paperclip docs. Overridable per
# instance via `paperclip.poll_schedule` in instance.yaml (ADR-0014).
DEFAULT_POLL_CRON="*/5 * * * *"

# --- 1. instance.yaml bootstrap / reuse -------------------------------------------------------
if [ ! -f "${INSTANCE_CONFIG}" ]; then
  echo "[bootstrap] no ${INSTANCE_CONFIG} found — writing the default configuration template"
  mkdir -p "$(dirname "${INSTANCE_CONFIG}")"
  cp "${DEFAULT_INSTANCE_CONFIG}" "${INSTANCE_CONFIG}"
  echo "[bootstrap] edit it on the host volume, then restart this container to apply your settings"
else
  echo "[bootstrap] reusing existing ${INSTANCE_CONFIG}"
fi

# --- 2. Resolve instance.yaml into the generated env file --------------------------------------
# `// ""` makes a missing or null field read as an empty string rather than the literal "null",
# so every consumer below only has to test for emptiness.
read_cfg() {
  yq "${1} // \"\"" "${INSTANCE_CONFIG}"
}

AGENT_PERSONAS="$(yq '(.personas // []) | join(",")' "${INSTANCE_CONFIG}")"
MODEL_HOST_PROVIDER="$(read_cfg '.model_host.provider')"
MODEL_HOST_CREDENTIALS_REF="$(read_cfg '.model_host.credentials_ref')"
PAPERCLIP_AGENT_ID="$(read_cfg '.paperclip.agent_id')"
PAPERCLIP_API_KEY_REF="$(read_cfg '.paperclip.api_key_ref')"
PAPERCLIP_POLL_SCHEDULE="$(read_cfg '.paperclip.poll_schedule')"
GITHUB_BOT_REF="$(read_cfg '.identity.github_bot_account_ref')"

# Dereference a *_ref field: $1 is the name of the env var the config points at, $2 is a label for
# diagnostics. Echoes the resolved value, or nothing. A ref naming a variable that isn't present in
# the container's environment is the single most common misconfiguration here (a typo in
# instance.yaml, or a .env/Secrets Manager entry that was never added), and it used to fail
# silently — so say so on stderr rather than writing an empty credential and letting the tool fail
# later with something unrelated.
resolve_ref() {
  local ref_name="$1" label="$2" value
  [ -n "${ref_name}" ] || return 0
  # Validate before dereferencing. `${!name}` on something that isn't a valid identifier is a "bad
  # substitution" in some bash versions and silently empty in others, so check explicitly rather
  # than depending on which bash the base image happens to ship. This catches the mistake of putting
  # a credential *value* (or a `$VAR` expression) in a *_ref field instead of a variable name.
  if [[ ! "${ref_name}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "[bootstrap] WARNING: ${label} is '${ref_name}', which is not a valid environment variable" \
         "name — these fields name a variable, they do not hold its value. Ignoring it." >&2
    return 0
  fi
  value="${!ref_name:-}"
  if [ -z "${value}" ]; then
    echo "[bootstrap] WARNING: ${label} references '${ref_name}', but no such variable is set in" \
         "this container's environment — check your .env file or secret mapping" >&2
    return 0
  fi
  printf '%s' "${value}"
}

MODEL_HOST_API_KEY="$(resolve_ref "${MODEL_HOST_CREDENTIALS_REF}" 'model_host.credentials_ref')"
PAPERCLIP_AGENT_API_KEY="$(resolve_ref "${PAPERCLIP_API_KEY_REF}" 'paperclip.api_key_ref')"
GITHUB_TOKEN_VALUE="$(resolve_ref "${GITHUB_BOT_REF}" 'identity.github_bot_account_ref')"

mkdir -p "${HERMES_HOME}"
# Regenerated on every start, so instance.yaml is always the source of truth. Written with a
# restrictive mode before any credential lands in it.
umask 077
{
  echo "# Generated by harness-bootstrap.sh from ${INSTANCE_CONFIG} — do not edit by hand."
  echo "# Regenerated on every container start; edit ${INSTANCE_CONFIG} instead."
  [ -n "${AGENT_PERSONAS}" ]          && echo "AGENT_PERSONAS=${AGENT_PERSONAS}"
  [ -n "${MODEL_HOST_PROVIDER}" ]     && echo "MODEL_HOST_PROVIDER=${MODEL_HOST_PROVIDER}"
  [ -n "${MODEL_HOST_API_KEY}" ]      && echo "MODEL_HOST_API_KEY=${MODEL_HOST_API_KEY}"
  [ -n "${PAPERCLIP_AGENT_ID}" ]      && echo "PAPERCLIP_AGENT_ID=${PAPERCLIP_AGENT_ID}"
  [ -n "${PAPERCLIP_AGENT_API_KEY}" ] && echo "PAPERCLIP_AGENT_API_KEY=${PAPERCLIP_AGENT_API_KEY}"
  [ -n "${GITHUB_TOKEN_VALUE}" ]      && echo "GITHUB_TOKEN=${GITHUB_TOKEN_VALUE}"
  true
} > "${HERMES_ENV_FILE}"
umask 022
# `>` truncates but preserves an existing file's mode, so set it explicitly rather than relying on
# the umask above having applied on this particular start.
chmod 600 "${HERMES_ENV_FILE}"

echo "[bootstrap] wrote ${HERMES_ENV_FILE} (personas='${AGENT_PERSONAS:-none}'," \
     "model host='${MODEL_HOST_PROVIDER:-unset}', paperclip agent='${PAPERCLIP_AGENT_ID:-unset}')"

# Also export the resolved values into this shell's environment. Because this file is *sourced* by
# the entrypoint (which then becomes/launches the long-running processes), these are inherited by
# Hermes and by everything Hermes spawns — which is what makes the resolved credentials usable by
# tools that read the environment directly rather than Hermes's env file. In particular `gh` picks
# up GITHUB_TOKEN this way, so `gh auth status` works inside a running container whatever the
# swarm owner named the underlying *_ref variable.
export AGENT_PERSONAS MODEL_HOST_PROVIDER PAPERCLIP_AGENT_ID
[ -n "${MODEL_HOST_API_KEY}" ]      && export MODEL_HOST_API_KEY
[ -n "${PAPERCLIP_AGENT_API_KEY}" ] && export PAPERCLIP_AGENT_API_KEY
[ -n "${GITHUB_TOKEN_VALUE}" ]      && export GITHUB_TOKEN="${GITHUB_TOKEN_VALUE}"
true   # keep the conditional exports above from deciding this script's exit status under `set -e`

# --- 3. Paperclip work-poll cron job ----------------------------------------------------------
POLL_CRON="${PAPERCLIP_POLL_SCHEDULE:-}"
[ -n "${POLL_CRON}" ] || POLL_CRON="${DEFAULT_POLL_CRON}"
POLL_COMMAND="paperclipai agent inbox-mine --user-id ${PAPERCLIP_AGENT_ID} --status todo,in_progress"
CRON_JOBS_FILE="${HERMES_HOME}/cron/jobs.json"

# This runs on every container start, not just the first. Whether `hermes cron create` itself
# dedupes an identical schedule+command is unconfirmed upstream, so guard explicitly by checking
# the jobs file for the exact command — that keeps restarts from accumulating duplicate poll jobs
# regardless of Hermes's own behavior.
if [ -n "${PAPERCLIP_AGENT_ID}" ]; then
  if [ -f "${CRON_JOBS_FILE}" ] && grep -qF "${POLL_COMMAND}" "${CRON_JOBS_FILE}"; then
    echo "[bootstrap] Paperclip poll job already registered — not creating a duplicate"
  else
    echo "[bootstrap] registering Paperclip poll job on schedule '${POLL_CRON}'"
    hermes cron create "${POLL_CRON}" "${POLL_COMMAND}" \
      || echo "[bootstrap] WARNING: 'hermes cron create' failed — this instance will not pull work" \
              "until the job is registered; continuing so the container still starts" >&2
  fi
else
  echo "[bootstrap] paperclip.agent_id is unset in ${INSTANCE_CONFIG} — skipping poll-job" \
       "registration. This instance will not receive work until it is set and the container" \
       "restarted (see configuration-docs/paperclip-agent-registration.md)."
fi
